### ISSUE TITLE
How to install this.

### ISSUE THREAD

**Issue by bLackCat-79** [b4dpxl/otx_to_opencti#1]
Hey,

Can you make a little guide on how to install this connector?
Is it just adding to the docker-compose.yml file?

**Comment by bLackCat-79** [comment]
PS: yeey! I made the first issue :)

**Comment by b4dpxl** [comment]
It's created to be run standalone, not as part of the main docker container. Copy `config.cfg.sample` to `config.cfg`, make sure everything in the `OTX` and `OpenCTI` sections is completed, check you can connect to RabbitMQ (might need to change your docker config for that to be exposed), and run the python script.

This is nowhere near production ready; I only published this here as a starter for the OpenCTI project.
